ScottLogic/openapi-forge

features/querystring.feature

Fixes test cases relating to default parameters, see https://github.com/ColinEberhardt/openapi-forge/pull/1/files#diff-ab26b8d33990bbf874d20cfb0e380c7cfc7b40e91161d4a2354bf78b16405803L48-L49
@murcikan-scottlogic

Test case fix

---

features/objects.feature
features/pathparams.feature
features/querystring.feature
src/transformers.js

added feature tests for correct default serialization of array and object parameters both in path and query

feat: set parameter serialization when missing

---

src/generate.js
src/index.js

User experience - better error reporting

---

README.md
package-lock.json
package.json
src/generate.js
src/index.js

see: https://github.com/ScottLogic/openapi-forge/issues/3 (still need to add support for npm package)
this will also make #10 a lot easier

feat: allow specification of a generator via a git URL

---

src/transformers.js

e.g. param.schema.default=0 or param.schema.default=false

fix: handle 0 or false default params

---

features/objects.feature
features/pathparams.feature
features/querystring.feature
features/requestBody.feature

just to take the guess work out of what parameter type we are working with

chore: standardised feature parameters description

---

README.md
src/index.js

fix various typos in documentation

fix typos in documentation

---

README.md
src/generate.js
src/index.js
src/log.js

- Add a verbose option -v that adds more information and fire to the command line output.
- Silenced output from shell.exec
- Only show error stack with verbose output
- Update documentation to include -v option

Increase API generation report verbosity

---

src/generate.js

PR for https://github.com/ScottLogic/openapi-forge/issues/49
- Add test to see if errors object is loopable. 
- Add test to see if errors.instancePath is defined before adding it to error message

Schema validation error logging bug

---

src/transformers.js

This pull request fixes the stack overflow bug.
**Changes:**
- resolveReferences() now uses loops instead of recursion

35-Resolving $ref references can result in stack overflow fix

---

README.md
features/headerParams.feature

- Add the Gherkin test scenario for header parameters
- Fix typo in the Readme file

Add the Gherkin test scenario for header parameters

---

src/generate.js

If not then see if it is a URL
PR for issue: https://github.com/ScottLogic/openapi-forge/issues/63

fix bug by first checking if file path exists

---

src/log.js

PR for issue: https://github.com/ScottLogic/openapi-forge/issues/82

Show errors when using log level --quiet

---

src/generate.js
src/generatorResolver.js
src/testResultParser.js

Fix new prettier errors brought in during recent commits

fix new prettier errors

---

features/components.feature
features/configuration.feature
features/cookieParams.feature
features/headerParams.feature
features/model.feature
features/objects.feature
features/pathparams.feature
features/querystring.feature
features/requestBody.feature
features/response.feature

PR for issue: https://github.com/ScottLogic/openapi-forge/issues/104
linked PRs: 
https://github.com/ScottLogic/openapi-forge-csharp/pull/25
https://github.com/ScottLogic/openapi-forge-typescript/pull/23

test: make schemas valid

---

package.json

PR for issue: https://github.com/ScottLogic/openapi-forge/issues/5

docs: add engine to package.json

---

.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/test.yml
.husky/pre-commit
CONTRIBUTING.md
package-lock.json
package.json
src/generate.js

Move formatting from forge to individual generators

move formatting to generators

---

.github/workflows/test.yml

PR for issue: https://github.com/ScottLogic/openapi-forge/issues/127

ci: stop early ending of workflow on error

---

src/generate.js

fixes:  https://github.com/ScottLogic/openapi-forge/issues/135

fix: prevent change of directory during formatting

---

src/generate.js

fix: formatting uses ES module rather than running a shell command

---

.github/workflows/test-forge.yml

This PR will have no effect until https://github.com/ScottLogic/openapi-forge/pull/149 is merged in.

chore: add forge Jest tests to continous integration

---

src/common/log.js
src/forge/index.js
src/generate.js

fixes #190 
Quiet output:
~~~
% node ./src/index.js forge https://petstore3.swagger.io/api/v3/openapi.json ../openapi-forge-typescript -o api --logLevel q
API generation SUCCESSFUL
~~~
Standard output:
~~~
% node ./src/index.js forge https://petstore3.swagger.io/api/v3/openapi.json ../openapi-forge-typescript -o api             
Loading generator from '../openapi-forge-typescript'
Validating generator
Loading schema from 'https://petstore3.swagger.io/api/v3/openapi.json'
Validating schema
Iterating over 10 files
---------------------------------------------------
API generation  SUCCESSFUL 
---------------------------------------------------
Your API has been forged from the fiery furnace:
8 models have been molded
13 endpoints have been cast …

Minor logging improvements

---

package.json

test: suppress logging when running jest
