ScottLogic/openapi-forge

README.md
If you only 'npm install --global' there will be missing dependencies.
As this is not an npm package yet all that npm does is in the global node_modules directory is to link to the local openapi-forge node_modules directory.
So first install locally so all dependencies are placed in local node_modules then install globally to link to global node_modules directory and allow execution of 'openapi-forge forge' command globally.
=> Fix Quick Start documentation

README.md, src/generate.js, src/index.js
PR for https://github.com/ScottLogic/openapi-forge/issues/3
- Allow the use of npm packages for generators.
- Checks if package exists before trying to install it.
- Checks if there is a local generator before trying to find an npm module. Uses current working directory to form paths to modules.
- Install location is in node_modules directory of openapi-forge.
- Updated documentation.
- Create new function `loadGenerator()` to keep `generate()` clean and also to match `loadSchema()`.
- Change `generatorUrlOrPath `-> `generatorPathOrUrl `to align with `schemaPathOrUrl`.
=> Npm generator

package-lock.json, package.json, src/generate.js
PR for https://github.com/ScottLogic/openapi-forge/issues/9
Using API endpoint `https://converter.swagger.io/api/convert` to convert to OpenAPI v3.
I have tested v2 of the petstore in both yaml & json format. I have not found a OpenAPI v1 schema to test but the documentation for the endpoint states it can handle both v1 & v2 schemas.
There is no way to know what version of OpenAPI the schema currently is so all schemas are converted.
=> Add converting of schemas using swagger/convert API endpoint

src/generate.js
PR related to https://github.com/ScottLogic/openapi-forge/issues/54
Language specific testing fails due to the schema object structure being different (in some test cases there are no endpoints or models). I have added null checking to prevent this.
=> Add null checking to schema structure

README.md, src/index.js, src/log.js
This PR is related to https://github.com/ScottLogic/openapi-forge/issues/54
Add a new log level that stops all CL output for use in automated systems. 
This is also needed for the language specific generator testing.
=> Add 'quiet' log level

.gitignore, README.md, src/generate.js, src/generatorResolver.js, src/index.js, src/log.js, src/testGenerators.js, src/testResultParser.js
PR related to issue  https://github.com/ScottLogic/openapi-forge/issues/10
PR related to PR https://github.com/ScottLogic/openapi-forge-typescript/pull/8
Using openapi-forge test-generators you can test all language generators and then have a table of results presented. 
This command searches for a local language generators or uses the version hosted on GitHub.
=> Test all language generators in one command

features/objects.feature, features/pathparams.feature, features/querystring.feature, features/requestBody.feature
Single quotes are not valid!
Originally the outer quotes were used as part of the step definition regex. However, the nested quotes look quite confusing, and the regex doesn't really need them to locate the parameter
=> test: single quotes are not valid JSON

features/objects.feature
The `%20` encoding is used before the querystring, and `+` after. Because, why not?
ref: https://stackoverflow.com/a/1634293/249933
=> test: fix the querystring character encoding

src/index.js, src/testGenerators.js
fix bug found when demoing feature to team.
The default and custom paths to local generators were resolving incorrectly.
=> fix custom path in test-generators command

src/generate.js
NPM package Handlebars is needed when forging and therefore installing the dependencies is required when using a generator from GitHub.
PR for https://github.com/ScottLogic/openapi-forge/issues/70
=> Install generator dependencies when from GitHub

package-lock.json, package.json
Move prettier back to normal dependency as it is needed in the generate command.
=> Add prettier to dependency to fix testing

features/pathparams.feature
There was one more scenario that failed in the TypeScript generator. The commas needed encoding. A missed change from https://github.com/ScottLogic/openapi-forge/pull/75 which i also missed in the review
=> Fix failing scenario (encode commas in URL)

src/transformers.js
Allow check for sub object before accessing in resolveResponse() & handle different content types in addRequestBodyToParams()
=> fix: fix TypeScript testing

README.md, package-lock.json, src/generate.js, src/generatorResolver.js, src/testGenerators.js
PR for issue: https://github.com/ScottLogic/openapi-forge/issues/53
- NPM packages only used when generating. 
- Add missing husky install script
- Misc refactoring of generator retrieval.
- Update README.md
Side Notes
- When testing the repo is cloned. This is due to the TypeScript testing not finding some 'required'. I have a suspicion that this is due to the nesting of npm modules and cucumber-js resolving relative/partial file paths incorrectly (to the wrong level of npm module.  I copied the typescript generator module out of the forge and the tests started working without changing anything.
- There are no versioning problems as it always clone the most recent commit to main when testing.
=> ci: use NPM packages when generating

features/tags.feature, package-lock.json, src/generate.js, src/helpers.js, src/transformers.js
PR for issue: https://github.com/ScottLogic/openapi-forge/issues/18
Separate paths by first tag in 'tags' array
During transformation phase a _tags array is generated from the tags that are present in the paths. This is due to the actual tags array not being a full list of tags and a schema can be valid if a tag is only present in the path and not in tags array.
Path is placed in file that corresponds to the first element in path tag array or a 'tagless' API file if no path tags array.
This stops loss of paths if path tag is not in schema tags array.
=> feat: group by tag

CODE_OF_CONDUCT.md
I have used the [contributor-covenant](https://www.contributor-covenant.org/) v2.1 code of conduct template. It uses a [CC BY 4.0 License](https://github.com/EthicalSource/contributor_covenant/blob/release/LICENSE.md) and has a very extensive set of rules for a healthy work environment.
Related issue: https://github.com/ScottLogic/openapi-forge/issues/48
=> docs: add code of conduct file

src/generatorResolver.js
closes: #132 
using path creation form path module to make path generation platform agnostic.
@ColinEberhardt can you please test this on mac to see if it works.
=> fix: make path creation platform agnostic

.github/workflows/test.yml, package.json, src/index.js, src/testGenerators.js
see:
https://github.com/ScottLogic/openapi-forge-typescript/pull/39
https://github.com/ScottLogic/openapi-forge-javascript/pull/2
https://github.com/ScottLogic/openapi-forge-csharp/pull/39
Updated the tests to use the [cucumber messages](https://github.com/cucumber/messages) format output. Note, this is not supported in C#, so have added a somewhat hacky solution.
Also, the tests are now hard-coded to assume that the generators and forge are in the same folder, removing the need for passing any arguments.
=> test: simplify the generator tests

src/transformers.js
this prevents the generators creating empty include statements
=> fix: only add inline objects prop to the schema if it exists

.eslintignore, .gitattributes, package-lock.json, package.json, src/generate.js, test/generate.test.js
**What:**
- The forge can now copy and transform files that are nested in sub-directories inside the template/ directory.
- Some unit tests written for the forge's JS code.
- Small git, eslint and npm package fixes.
**Why:**
- When starting to create a Java (Maven) generator, we realised that if we want to minimise our users' effort to get an initial working example, we need to output our transformed files in Maven's directory structure (src/main/java/<package>/<file>). This PR adds support for this.
**Caveats:**
- No CI/CD setup for these new tests.
=> Feature: Recursive directory copying for files in template/

src/forge/index.js, src/generate.js, test/generate.test.js
The test-generators command was no longer working following https://github.com/ScottLogic/openapi-forge/pull/160/files because of the change to the generate function in generate.js. This PR reverts the changes, but keeps the functionality needed for the generator-options command.
Hopefully this kind of error will be picked up much more easily when we've addressed https://github.com/ScottLogic/openapi-forge/issues/163
=> fix: test-generators command by reverting generate

features/response.feature
Partially implements https://github.com/ScottLogic/openapi-forge/issues/77 by exposing response headers, but does not apply the type information that may be present in the schema
=> test: add test to verify headers are supported
